
CREATE TABLE ANSWERS
(
  ANSWER_KEY INT          NOT NULL,
  ANSWERS    VARCHAR(200) NULL    ,
  PRIMARY KEY (ANSWER_KEY)
);

CREATE TABLE QUESTIONS
(
  QUESTION_KEY INT          NOT NULL,
  QUESTION     VARCHAR(200) NULL    ,
  PRIMARY KEY (QUESTION_KEY)
);

CREATE TABLE QUESTIONS_AND_ANSWERS
(
  ANSWER_KEY   INT NOT NULL,
  TOTAL_KEY    INT NOT NULL,
  QUESTION_KEY INT NOT NULL,
  PRIMARY KEY (TOTAL_KEY)
);

CREATE TABLE RESPONSES
(
  RESPONSE_NUMBER INT          NOT NULL,
  NAME            VARCHAR(200) NULL    ,
  PRIMARY KEY (RESPONSE_NUMBER)
);

CREATE TABLE TOTAL_QUESTIONS
(
  RESPONSE_NUMBER INT NOT NULL,
  TOTAL_KEY       INT NOT NULL
);

ALTER TABLE TOTAL_QUESTIONS
  ADD CONSTRAINT FK_RESPONSES_TO_TOTAL_QUESTIONS
    FOREIGN KEY (RESPONSE_NUMBER)
    REFERENCES RESPONSES (RESPONSE_NUMBER);

ALTER TABLE QUESTIONS_AND_ANSWERS
  ADD CONSTRAINT FK_ANSWERS_TO_QUESTIONS_AND_ANSWERS
    FOREIGN KEY (ANSWER_KEY)
    REFERENCES ANSWERS (ANSWER_KEY);

ALTER TABLE TOTAL_QUESTIONS
  ADD CONSTRAINT FK_QUESTIONS_AND_ANSWERS_TO_TOTAL_QUESTIONS
    FOREIGN KEY (TOTAL_KEY)
    REFERENCES QUESTIONS_AND_ANSWERS (TOTAL_KEY);

ALTER TABLE QUESTIONS_AND_ANSWERS
  ADD CONSTRAINT FK_QUESTIONS_TO_QUESTIONS_AND_ANSWERS
    FOREIGN KEY (QUESTION_KEY)
    REFERENCES QUESTIONS (QUESTION_KEY);
